version: '3.8'

# ---------------------------------------------------------------------------- #

services:
  wordpress:
    container_name: inception_wordpress
    build: services/wordpress
    ports:
      - "9000"
    networks:
      - net_inception
    volumes:
      - "${VOLUMES_LOCATION}/v_wordpress:/var/www/html:rw"
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"
    restart: always
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cgi-fcgi", "-connect", "localhost:9000", "/status"]
      interval: 5s
      timeout: 1s
      retries: 30
      start_period: 5s

# ---------------------------------------------------------------------------- #

  nginx:
    container_name: inception_nginx
    build: services/nginx
    ports:
      - "443:443"
    networks:
      - net_inception
    volumes:
      - "${VOLUMES_LOCATION}/v_wordpress:/var/www/html:rw"
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress
      - grafana

# ---------------------------------------------------------------------------- #

  mariadb:
    container_name: inception_mariadb
    build: services/mariadb
    volumes:
      - ${VOLUMES_LOCATION}/v_database:/var/lib/mysql:rw
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"
    ports:
      - "3306"
    networks:
      - net_inception
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 5s

# ---------------------------------------------------------------------------- #

  redis:
    container_name: inception_redis
    build: services/bonus/redis
    volumes:
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"
    ports:
      - "6379"
    networks:
      - net_inception
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 1s

# ---------------------------------------------------------------------------- #

  ftp:
    container_name: inception_ftp
    build: services/bonus/ftp
    volumes:
      - ${VOLUMES_LOCATION}/v_wordpress/wordpress:/srv:rw
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"
    ports:
      - "21:21"
    networks:
      - net_inception
    restart: always
    env_file:
      - .env

# ---------------------------------------------------------------------------- #

  grafana:
    container_name: inception_grafana
    build: services/bonus/grafana
    volumes:
      - ${VOLUMES_LOCATION}/v_grafana:/var/lib/grafana:rw
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"
    ports:
      - "3000"
    networks:
      - net_inception
    restart: always
    env_file:
      - .env

# ---------------------------------------------------------------------------- #

  prometheus:
    container_name: inception_prometheus
    build: services/bonus/prometheus
    volumes:
      - ${VOLUMES_LOCATION}/v_prometheus:/var/lib/prometheus:rw
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"
    ports:
      - "9090"
    networks:
      - net_inception
    restart: always
    env_file:
      - .env

# ---------------------------------------------------------------------------- #

  node_exporter:
    container_name: inception_node_exporter
    build: services/bonus/node_exporter
    ports:
      - "9100"
    networks:
      - net_inception
    restart: always
    env_file:
      - .env
    volumes:
      - /:/rootfs:ro,rslave
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"

# ---------------------------------------------------------------------------- #

  loki:
    container_name: inception_loki
    build: services/bonus/loki
    ports:
      - "3100:3100"
    networks:
      - net_inception
    restart: always
    env_file:
      - .env

# ---------------------------------------------------------------------------- #

  promtail:
    container_name: inception_promtail
    build: services/bonus/promtail
    ports:
      - "9080:9080"
    networks:
      - net_inception
    restart: always
    env_file:
      - .env
    volumes:
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"

# ---------------------------------------------------------------------------- #

networks:
  net_inception: {}
