version: '3.8'

services:
  wordpress:
    container_name: inception_wordpress
    build: services/wordpress
    ports:
      - "9000:9000"
    networks:
      - net_inception
    volumes:
      - "${VOLUMES_LOCATION}/v_wordpress:/var/www/html:rw"
    restart: always

networks:
  net_inception: {}
