version: '3.8'

# ---------------------------------------------------------------------------- #

services:
  wordpress:
    container_name: inception_wordpress
    build: services/wordpress
    ports:
      - "9000"
    networks:
      - net_inception
    volumes:
      - "${VOLUMES_LOCATION}/v_wordpress:/var/www/html:rw"
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"
    restart: always
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: cgi-fcgi -connect localhost:9000 /status
      interval: 5s
      timeout: 1s
      retries: 30
      start_period: 5s

# ---------------------------------------------------------------------------- #

  nginx:
    container_name: inception_nginx
    build: services/nginx
    ports:
      - "443:443"
    networks:
      - net_inception
    volumes:
      - "${VOLUMES_LOCATION}/v_wordpress:/var/www/html:rw"
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"
    restart: always
    env_file: .env
    depends_on:
      wordpress:
        condition: service_healthy
      grafana:
        condition: service_healthy
    healthcheck:
      test: 'curl --insecure --fail --silent --show-error --location
        https://localhost:443/status'
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s

# ---------------------------------------------------------------------------- #

  mariadb:
    container_name: inception_mariadb
    build: services/mariadb
    volumes:
      - ${VOLUMES_LOCATION}/v_database:/var/lib/mysql:rw
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"
    ports:
      - "3306"
    networks:
      - net_inception
    restart: always
    env_file: .env
    healthcheck:
      test: mysqladmin ping --host=localhost --password="${MARIADB_ROOT_PASSWORD}"
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s

# ---------------------------------------------------------------------------- #

  redis:
    container_name: inception_redis
    build: services/bonus/redis
    volumes:
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"
    ports:
      - "6379"
    networks:
      - net_inception
    restart: always
    env_file: .env
    healthcheck:
      test: redis-cli PING
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 1s

# ---------------------------------------------------------------------------- #

  ftp:
    container_name: inception_ftp
    build: services/bonus/ftp
    volumes:
      - ${VOLUMES_LOCATION}/v_wordpress/wordpress:/srv:rw
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"
    ports:
      - "21:21"
    networks:
      - net_inception
    restart: always
    env_file: .env
    healthcheck:
      test: nc -z -v -w1 localhost 21
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 0s

# ---------------------------------------------------------------------------- #

  grafana:
    container_name: inception_grafana
    build: services/bonus/grafana
    volumes:
      - ${VOLUMES_LOCATION}/v_grafana:/var/lib/grafana:rw
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"
    ports:
      - "3000"
    networks:
      - net_inception
    restart: always
    env_file: .env
    healthcheck:
      test: 'curl --fail --silent --show-error --location http://localhost:3000/healthz'
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 0s

# ---------------------------------------------------------------------------- #

  prometheus:
    container_name: inception_prometheus
    build: services/bonus/prometheus
    volumes:
      - ${VOLUMES_LOCATION}/v_prometheus:/var/lib/prometheus:rw
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"
    ports:
      - "9090"
    networks:
      - net_inception
    restart: always
    env_file: .env

# ---------------------------------------------------------------------------- #

  node_exporter:
    container_name: inception_node_exporter
    build: services/bonus/node_exporter
    ports:
      - "9100"
    networks:
      - net_inception
    restart: always
    env_file: .env
    volumes:
      - /:/rootfs:ro,rslave
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"

# ---------------------------------------------------------------------------- #

  loki:
    container_name: inception_loki
    build: services/bonus/loki
    ports:
      - "3100"
    networks:
      - net_inception
    restart: always
    env_file: .env

# ---------------------------------------------------------------------------- #

  promtail:
    container_name: inception_promtail
    build: services/bonus/promtail
    ports:
      - "9080"
    networks:
      - net_inception
    restart: always
    env_file: .env
    volumes:
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"

# ---------------------------------------------------------------------------- #

  cadvisor:
    container_name: inception_cadvisor
    build: services/bonus/cadvisor
    ports:
      - "8080"
    networks:
      - net_inception
    restart: always
    env_file: .env
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
      - "${VOLUMES_LOCATION}/v_logs:/var/log:rw"

# ---------------------------------------------------------------------------- #

networks:
  net_inception: {}
