version: '3.8'

services:
  wordpress:
    container_name: inception_wordpress
    build: services/wordpress
    ports:
      - "9000"
    networks:
      - net_inception
    volumes:
      - "${VOLUMES_LOCATION}/v_wordpress:/var/www/html:rw"
    restart: always
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    container_name: inception_nginx
    build: services/nginx
    ports:
      - "443:443"
    networks:
      - net_inception
    volumes:
      - "${VOLUMES_LOCATION}/v_wordpress:/var/www/html:rw"
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress
      - grafana

  mariadb:
    container_name: inception_mariadb
    build: services/mariadb
    volumes:
      - ${VOLUMES_LOCATION}/v_database:/var/lib/mysql:rw
    ports:
      - "3306"
    networks:
      - net_inception
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 5s

  redis:
    container_name: inception_redis
    build: services/bonus/redis
    ports:
      - "6379"
    networks:
      - net_inception
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 1s

  ftp:
    container_name: inception_ftp
    build: services/bonus/ftp
    volumes:
      - ${VOLUMES_LOCATION}/v_wordpress/wordpress:/srv:rw
    ports:
      - "20-21:20-21"
    networks:
      - net_inception
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress

  grafana:
    container_name: inception_grafana
    build: services/bonus/grafana
    volumes:
      - ${VOLUMES_LOCATION}/v_prometheus:/var/lib/grafana:rw
    ports:
      - "3000"
    networks:
      - net_inception
    restart: always
    env_file:
      - .env

  prometheus:
    container_name: inception_prometheus
    build: services/bonus/prometheus
    volumes:
      - ${VOLUMES_LOCATION}/v_prometheus:/var/lib/prometheus:rw
    ports:
      - "9090"
    networks:
      - net_inception
    restart: always
    env_file:
      - .env

  node_exporter:
    container_name: inception_node_exporter
    build: services/bonus/node_exporter
    ports:
      - "9100"
    networks:
      - net_inception
    restart: always
    env_file:
      - .env
    volumes:
      - /:/rootfs:ro,rslave

  # https://github.com/grafana/grafana
  # https://github.com/prometheus/prometheus
  # https://github.com/grafana/loki

networks:
  net_inception: {}
