version: '3.8'

services:
  mariadb:
    container_name: inception_mariadb
    build: services/mariadb
    volumes:
      - ${VOLUMES_LOCATION}/v_database:/var/lib/mysql:rw
    ports:
      - "3306"
    networks:
      - net_inception

networks:
  net_inception: {}
