version: '3.8'

services:
  wordpress:
    container_name: inception_wordpress
    build: services/wordpress
    ports:
      - "9000"
    networks:
      - net_inception
    volumes:
      - "${VOLUMES_LOCATION}/v_wordpress:/var/www/wordpress:rw"
  nginx:
    container_name: inception_nginx
    build: services/nginx
    ports:
      - "8080:80"
      - "443:443"
  mariadb:
    container_name: inception_mariadb
    build: services/mariadb
    volumes:
      - ${VOLUMES_LOCATION}/v_database:/var/lib/mysql:rw
    ports:
      - "3306"
    networks:
      - net_inception

networks:
  net_inception: {}
