version: '3.8'

services:
  wordpress:
    container_name: inception_wordpress
    build: services/wordpress
    ports:
      - "9000"
    networks:
      - net_inception
    volumes:
      - "${VOLUMES_LOCATION}/v_wordpress:/var/www/html:rw"
    restart: always
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    container_name: inception_nginx
    build: services/nginx
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - net_inception
    volumes:
      - "${VOLUMES_LOCATION}/v_wordpress:/var/www/html:rw"
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress

  mariadb:
    container_name: inception_mariadb
    build: services/mariadb
    volumes:
      - ${VOLUMES_LOCATION}/v_database:/var/lib/mysql:rw
    ports:
      - "3306"
    networks:
      - net_inception
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 2s

networks:
  net_inception: {}
