version: '3.8'

services:
  nginx:
    container_name: inception_nginx
    build: services/nginx
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - net_inception

networks:
  net_inception: {}
