version: '3.8'

# ---------------------------------------------------------------------------- #

services:
  wordpress:
    container_name: wordpress
    build: services/wordpress
    ports:
      - "9000"
    networks:
      - net_inception
    volumes:
      - "v_wordpress:/var/www/html:rw"
      - "v_logs:/var/log:rw"
    restart: unless-stopped
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: cgi-fcgi -connect localhost:9000 /status
      interval: 5s
      timeout: 1s
      retries: 30
      start_period: 5s

# ---------------------------------------------------------------------------- #

  nginx:
    container_name: nginx
    build: services/nginx
    ports:
      - "443:443"
    networks:
      - net_inception
    volumes:
      - "v_wordpress:/var/www/html:rw"
      - "v_logs:/var/log:rw"
    restart: unless-stopped
    env_file: .env
    depends_on:
      wordpress:
        condition: service_healthy
      grafana:
        condition: service_healthy
    healthcheck:
      test: 'curl --insecure --fail --silent --show-error --location
        https://localhost:443/status'
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s

# ---------------------------------------------------------------------------- #

  mariadb:
    container_name: mariadb
    build: services/mariadb
    volumes:
      - "v_database:/var/lib/mysql:rw"
      - "v_logs:/var/log:rw"
    ports:
      - "3306"
    networks:
      - net_inception
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: mysqladmin ping --host=localhost --password="${MARIADB_ROOT_PASSWORD}"
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s

# ---------------------------------------------------------------------------- #

  redis:
    container_name: redis
    build: services/bonus/redis
    volumes:
      - "v_logs:/var/log:rw"
    ports:
      - "6379"
    networks:
      - net_inception
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: redis-cli PING
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 1s

# ---------------------------------------------------------------------------- #

  ftp:
    container_name: ftp
    build: services/bonus/ftp
    volumes:
      - "v_wordpress:/srv:rw"
      - "v_logs:/var/log:rw"
    ports:
      - "21:21"
    networks:
      - net_inception
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: nc -z -v -w1 localhost 21
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 0s

# ---------------------------------------------------------------------------- #

  grafana:
    container_name: grafana
    build: services/bonus/grafana
    volumes:
      - "v_grafana:/var/lib/grafana:rw"
      - "v_logs:/var/log:rw"
    ports:
      - "3000"
    networks:
      - net_inception
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: 'curl --fail --silent --show-error --location http://localhost:3000/healthz'
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 0s

# ---------------------------------------------------------------------------- #

  prometheus:
    container_name: prometheus
    build: services/bonus/prometheus
    volumes:
      - "v_prometheus:/var/lib/prometheus:rw"
      - "v_logs:/var/log:rw"
    ports:
      - "9090"
    networks:
      - net_inception
    restart: unless-stopped
    env_file: .env

# ---------------------------------------------------------------------------- #

  node_exporter:
    container_name: node_exporter
    build: services/bonus/node_exporter
    ports:
      - "9100"
    networks:
      - net_inception
    restart: unless-stopped
    env_file: .env
    volumes:
      - "/:/rootfs:ro,rslave"
      - "v_logs:/var/log:rw"

# ---------------------------------------------------------------------------- #

  loki:
    container_name: loki
    build: services/bonus/loki
    ports:
      - "3100"
    networks:
      - net_inception
    restart: unless-stopped
    env_file: .env

# ---------------------------------------------------------------------------- #

  promtail:
    container_name: promtail
    build: services/bonus/promtail
    ports:
      - "9080"
    networks:
      - net_inception
    restart: unless-stopped
    env_file: .env
    volumes:
      - "v_logs:/var/log:rw"

# ---------------------------------------------------------------------------- #

  cadvisor:
    container_name: cadvisor
    build: services/bonus/cadvisor
    ports:
      - "8080"
    networks:
      - net_inception
    restart: unless-stopped
    env_file: .env
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
      - "v_logs:/var/log:rw"

# ---------------------------------------------------------------------------- #

volumes:
  v_logs:
    # driver: local
    # driver_opts:
      # type: none
      # device: ${VOLUMES_LOCATION}/v_logs
      # o: bind
  v_database:
    # driver: local
    # driver_opts:
      # type: none
      # device: ${VOLUMES_LOCATION}/v_database
      # o: bind
  v_wordpress:
    # driver: local
    # driver_opts:
      # type: none
      # device: ${VOLUMES_LOCATION}/v_wordpress
      # o: bind
  v_grafana:
    # driver: local
    # driver_opts:
      # type: none
      # device: ${VOLUMES_LOCATION}/v_grafana
      # o: bind
  v_prometheus:
    # driver: local
    # driver_opts:
      # type: none
      # device: ${VOLUMES_LOCATION}/v_prometheu
      # o: bind

networks:
  net_inception: {}
